CREATE TABLE IF NOT EXISTS weather
(
    id             INT8 GENERATED BY DEFAULT AS IDENTITY,
    avg_temp       FLOAT8 NOT NULL,
    avg_visibility FLOAT8 NOT NULL,
    city           VARCHAR(255),
    date           DATE,
    max_temp       FLOAT8 NOT NULL,
    max_wind_speed FLOAT8 NOT NULL,
    min_temp       FLOAT8 NOT NULL,
    PRIMARY KEY (id)
)